#!/usr/bin/env python3
"""Build skills.js (window.SKILLS) for IEOR E4741 from the real course sources.

Sources: course/hft-columbia/w1..w15.pptx (slide ranges verified), the
project-starter labs, Canvas assignments (course 252758, read-only), and the
exam bank group names in course/exams/hft_{midterm,final}_bank.json.
"""
import json, os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "skills.js")

CANVAS = "https://courseworks2.columbia.edu/courses/252758/assignments/"
LABS = "https://github.com/sdonadio/hft-cpp-starter-columbia/blob/main/labs/"
COMP = "https://sdonadio.github.io/low-latency-trading-arena/"

# ---------------------------------------------------------------- assignments
HW = {  # n -> (canvas id, name, due date in America/New_York)
    1:  (1714425, "HW 1 — Order-book metrics in C++", "2026-09-19"),
    2:  (1714426, "HW 2 — Pointers, references & the cost of a copy", "2026-09-26"),
    3:  (1714427, "HW 3 — Dynamic allocation, RAII & smart pointers", "2026-10-03"),
    4:  (1714428, "HW 4 — A high-performance allocator (Memory Triathlon)", "2026-10-10"),
    5:  (1714429, "HW 5 — Generic programming with the STL", "2026-10-17"),
    6:  (1714430, "HW 6 — CRTP & compile-time computation", "2026-10-17"),
    7:  (1714431, "HW 7 — A fast order book + a fast symbol map", "2026-10-24"),
    8:  (1714432, "HW 8 — Rolling event counter (sliding window)", "2026-10-31"),
    9:  (1714433, "HW 9 — A seqlock (one writer, many readers)", "2026-11-07"),
    10: (1714434, "HW 10 — An SPSC lock-free ring buffer", "2026-11-14"),
    11: (1714435, "HW 11 — A high-performance FIX parser", "2026-11-21"),
    12: (1714436, "HW 12 — Fast uint64 -> decimal (and a field encoder)", "2026-11-21"),
    13: (1714437, "HW 13 — Build Optimization (flags only)", "2026-11-28"),
    14: (1714438, "HW 14 — Profile and kill a latency tail", "2026-12-12"),
    15: (1714439, "HW 15 — Cross-venue stale-quote detector", "2026-12-19"),
}
PH = {  # phase -> (canvas id, name, due date ET)
    0: (1714412, "Project — Phase 0: Connect & Baseline", "2026-09-23"),
    1: (1714413, "Project — Phase 1: The Fast Hot Path", "2026-10-14"),
    2: (1714414, "Project — Phase 2: The Local Order Book", "2026-10-28"),
    3: (1714415, "Project — Phase 3: Threading to Accelerate", "2026-11-11"),
    4: (1714416, "Project — Phase 4: Multi-Process System with Shared-Memory Lock-Free IPC", "2026-11-21"),
    5: (1714417, "Project — Phase 5: Wire & Hardware Tuning", "2026-11-28"),
    6: (1714418, "Project — Phase 6: Profile & Kill the Tail", "2026-12-09"),
    7: (1714419, "Project — Phase 7: The Tournament", "2026-12-22"),
}
MID = {  # midterm bank group names
    "ptr": "Pointers, References & Memory Layout",
    "raii": "Allocation, RAII & Smart Pointers",
    "oop": "OOP, Virtual Dispatch & Object Model",
    "tpl": "Templates, CRTP & Compile-Time",
    "stl": "STL Containers & Algorithms",
    "cx": "Complexity, Cache & Performance Basics",
}
FIN = {  # final bank group names
    "core": "Core C++: Memory, RAII & Object Model",
    "tpl": "Templates, STL & Complexity",
    "thr": "Threads, Mutexes & Condition Variables",
    "atom": "Atomics, Memory Ordering & Lock-Free Queues",
    "cache": "Cache Effects, False Sharing & Data Layout",
    "simd": "Branch Prediction, SIMD & Compiler Optimisation",
    "net": "Networking: Sockets, Kernel Bypass & Protocol Parsing",
    "sys": "Low-Latency System Design: Allocators, Order Books & Timing",
    "meas": "Measurement, Tail Latency & Production Practice",
}

# session n -> decks, lab file numbers, hw number, project phase, exam
SESSIONS = [
    (1,  "2026-09-09", "HFT Landscape & Market Microstructure",            ["w1"],        [1],      1,  0, None),
    (2,  "2026-09-16", "C++ Performance Foundations",                      ["w2"],        [2],      2,  0, None),
    (3,  "2026-09-23", "Memory Management & Smart Pointers",               ["w3"],        [3],      3,  1, None),
    (4,  "2026-09-30", "Custom Allocators & Memory Pools",                 ["w4"],        [4],      4,  1, None),
    (5,  "2026-10-07", "Templates & Generic Programming + Compile-Time & Policy-Based Design (CRTP)",
                                                                           ["w5", "w6"],  [5, 6],   5,  1, None),
    (6,  "2026-10-14", "Data Structures for HFT — The Order Book",         ["w7"],        [7],      7,  2, None),
    (7,  "2026-10-21", "Algorithmic Complexity & Time-Series",             ["w8"],        [8],      8,  2, None),
    (8,  "2026-10-28", "Concurrency I — Atomics & Memory Models · Midterm",["w9"],        [9],      9,  3, "midterm"),
    (9,  "2026-11-04", "Concurrency II — Lock-Free Pipelines",             ["w10"],       [10],     10, 3, None),
    (10, "2026-11-11", "Network Protocols & Market Data + Async I/O & Serialization",
                                                                           ["w11", "w12"],[11, 12], 11, 4, None),
    (11, "2026-11-18", "Low-Latency Design — SIMD, Kernel Bypass & Colocation",
                                                                           ["w13"],       [13],     13, 5, None),
    (12, "2026-12-02", "Profiling, the Tail & Production",                 ["w14"],       [14],     14, 6, None),
    (13, "2026-12-09", "Latency Arbitrage, Multi-Venue & the Tournament · Final",
                                                                           ["w15"],       [15],     15, 7, "final"),
]

# ---------------------------------------------------------------- where helpers
def deck(session, w, slides):
    return {"type": "deck", "session": session, "label": "Deck %s · %s" % (w.upper(), slides)}

def lab(session, n, part):
    return {"type": "lab", "session": session,
            "label": "Lab week %d · %s" % (n, part),
            "url": "%sweek%02d.md" % (LABS, n)}

def hw(n):
    i, name, _ = HW[n]
    return {"type": "hw", "label": name, "url": CANVAS + str(i)}

def proj(p):
    i, name, _ = PH[p]
    return {"type": "project", "label": name, "url": CANVAS + str(i)}

def midterm(key):
    return {"type": "exam", "label": "Midterm · group: " + MID[key]}

def final(key):
    return {"type": "exam", "label": "Final · group: " + FIN[key]}

def S(sid, cat, name, can, intro, practised, depth, where, interview=False):
    return {"id": sid, "category": cat, "name": name, "can": can,
            "introduced": intro, "practised": practised, "depth": depth,
            "where": where, "interview": interview}

# ---------------------------------------------------------------- the skills
SKILLS = [
    # ------------------------------------------------------------- session 1
    S("trading.lob", "trading", "The central limit order book",
      "You can read a two-sided limit order book and compute the spread, mid, microprice and order-book imbalance from the top-of-book prices and sizes.",
      1, [6], 3,
      [deck(1, "w1", "slides 9\u201311"), deck(6, "w7", "slide 14"),
       lab(1, 1, "step 4 and the hand-computed book in Your turn"),
       hw(1), final("sys")], True),
    S("trading.price-time-priority", "trading", "Price-time priority & the FIFO queue",
      "You can apply price-then-time priority to say which resting order fills first, and explain why a cancel-and-repost sends you to the back of the queue.",
      1, [6, 13], 3,
      [deck(1, "w1", "slide 10"), deck(6, "w7", "slide 13"), deck(13, "w15", "slide 10"),
       hw(1), final("sys")], True),
    S("trading.tick-to-trade", "trading", "Tick-to-trade latency & the tail",
      "You can define tick-to-trade latency, report it as p50/p99/p99.9 instead of a mean, and explain why the tail is what decides an HFT race.",
      1, [12], 3,
      [deck(1, "w1", "slides 12, 18"), deck(12, "w14", "slides 5, 17"),
       lab(1, 1, "step 3 \u2014 the tick->order print"), proj(0), final("meas")], True),
    S("trading.fees-maker-taker", "trading", "Maker/taker fees & rebates",
      "You can work out whether a fill was actually profitable once the taker fee or maker rebate is applied to the notional.",
      1, [13], 2,
      [deck(1, "w1", "slide 11"), deck(13, "w15", "slide 9"),
       lab(1, 1, "step 3 \u2014 the FEE_SCHEDULE line")]),
    S("trading.colocation", "trading", "Colocation & the latency arms race",
      "You can explain what colocation buys and weigh a reduced venue latency tier against its cost using measured percentiles.",
      1, [11], 2,
      [deck(1, "w1", "slides 7, 13"), deck(11, "w13", "slides 11, 15"),
       lab(11, 13, "step 7 \u2014 colocation economics"), proj(5)]),
    S("tools.cmake-build", "tools", "Building a C++ project with CMake",
      "You can configure and build a C++ target with CMake and keep one build directory per flag set, so a cached flag never lies to you about what you measured.",
      1, [], 2,
      [deck(1, "w1", "slide 17"), lab(1, 1, "step 2 \u2014 build the arena C++ client"), proj(0)]),
    S("tools.arena-client", "tools", "Writing a bot on the arena C++ client",
      "You can subclass the arena WebSocket bot client, override on_book/on_fill/on_ack, and place or cancel orders from the hot path.",
      1, [6], 2,
      [deck(1, "w1", "slides 16\u201317"), deck(6, "w7", "slide 15"),
       lab(1, 1, "step 3 \u2014 connect and get on the board"), proj(0)]),
    S("tools.replay-harness", "tools", "Offline replay & percentile reporting",
      "You can replay a recorded tape through your bot offline and read the p50/p99/p99.9 table it prints, so an A/B change is measured rather than guessed.",
      1, [4, 11], 3,
      [deck(1, "w1", "slide 18"), deck(4, "w4", "slide 16"), deck(11, "w13", "slide 17"),
       proj(0), final("meas")]),

    # ------------------------------------------------------------- session 2
    S("cpp.pointers", "cpp", "Pointers & pointer arithmetic",
      "You can walk an array with a raw pointer, explain why p + 1 advances by sizeof(*p), and say why one-past-the-end may be formed but never dereferenced.",
      2, [], 3,
      [deck(2, "w2", "slides 7, 9\u201310"), hw(2), midterm("ptr")], True),
    S("cpp.pointers-vs-references", "cpp", "Pointers vs references, and const&",
      "You can choose between a pointer and a reference by asking whether 'absent' is a legal answer, and pass a large struct by const reference instead of by value.",
      2, [3], 3,
      [deck(2, "w2", "slide 8"), deck(3, "w3", "slides 15, 26"),
       lab(2, 2, "step 2 \u2014 stack vs heap and the honest sink"), hw(2), midterm("ptr")]),
    S("cpp.raw-allocation", "cpp", "malloc / calloc / new and the pairing rule",
      "You can pick between malloc, calloc, new and new[] for a given need and pair every allocation with its matching free, delete or delete[].",
      2, [3], 2,
      [deck(2, "w2", "slides 11\u201313, 17"), deck(3, "w3", "slide 6"),
       lab(3, 3, "step 1 \u2014 the raw new/delete bug"), hw(3), midterm("raii")]),
    S("perf.memory-hierarchy", "perf", "The memory hierarchy",
      "You can put rough numbers on a register, L1, L2, L3 and DRAM access and explain why a single miss to main memory costs about as much as a hundred L1 hits.",
      2, [], 3,
      [deck(2, "w2", "slides 5\u20136"), midterm("cx"), final("cache")], True),
    S("perf.cache-line-alignment", "perf", "The 64-byte cache line & alignment",
      "You can pack the fields a hot function reads onto one 64-byte cache line and use alignas to stop a hot object straddling two of them.",
      2, [], 3,
      [deck(2, "w2", "slide 21"), lab(2, 2, "step 4 \u2014 alignas(64)"), final("cache")], True),
    S("perf.false-sharing", "perf", "False sharing between cores",
      "You can recognise false sharing from a threaded version being slower than a single-threaded one, and fix it by giving each hot variable its own cache line.",
      2, [9], 3,
      [deck(2, "w2", "slide 22"), deck(9, "w10", "slide 14"),
       lab(2, 2, "step 4 \u2014 reproduce then fix false sharing"), final("cache")], True),
    S("perf.data-layout", "perf", "Data layout: contiguous, row-major, SoA vs AoS",
      "You can choose a contiguous layout over pointer chasing, order a nested loop so it walks memory in stride, and split the hot fields out of a struct a scan only partly reads.",
      2, [6, 7], 3,
      [deck(2, "w2", "slides 14\u201316, 18"), deck(6, "w7", "slide 9"), deck(7, "w8", "slide 6"),
       lab(2, 2, "step 3 \u2014 cache-friendly vs pointer-chasing"), hw(2), final("cache")], True),
    S("perf.branch-prediction", "perf", "Branch prediction & the pipeline",
      "You can explain what a mispredicted branch costs on a deep pipeline and name ways to make a hot branch predictable or remove it.",
      2, [12], 2,
      [deck(2, "w2", "slide 19"), deck(12, "w14", "slide 7"), final("simd")], True),
    S("tools.benchmarking", "tools", "Honest micro-benchmarking",
      "You can time a hot function with steady_clock in a release build, warm up first, keep the optimiser from deleting the work, and report percentiles rather than one mean.",
      2, [4, 6, 8, 9], 3,
      [deck(2, "w2", "slides 24, 26, 28"), lab(2, 2, "step 1 \u2014 your first honest micro-benchmark"),
       hw(2), final("meas")], True),

    # ------------------------------------------------------------- session 3
    S("cpp.classes-invariants", "cpp", "Classes, constructors & destructors",
      "You can establish a class invariant in the member-initialiser list, mark a converting constructor explicit, and predict construction and destruction order.",
      3, [5], 3,
      [deck(3, "w3", "slides 9\u201311, 18"), deck(5, "w5", "slides 16, 24"),
       hw(3), midterm("oop")]),
    S("cpp.rule-of-five", "cpp", "Rule of zero, rule of five",
      "You can decide whether a type needs none or all five special members, and explain why declaring a destructor alone silently kills the implicit moves.",
      3, [], 3,
      [deck(3, "w3", "slides 12\u201314"), lab(3, 3, "step 3 \u2014 the Rule of Three (and Five)"),
       hw(3), midterm("raii"), final("core")], True),
    S("cpp.move-semantics", "cpp", "Move semantics & std::move",
      "You can write a noexcept move constructor that steals and then blanks the source, and say what std::move actually does at the call site.",
      3, [], 3,
      [deck(3, "w3", "slides 13, 25"), hw(3), midterm("raii"), final("core")], True),
    S("cpp.raii", "cpp", "RAII \u2014 scope-bound resource management",
      "You can wrap a resource in a type that acquires in its constructor and releases in its destructor, so cleanup happens on every exit path including a throw.",
      3, [], 3,
      [deck(3, "w3", "slides 19, 26"), lab(3, 3, "step 4 \u2014 a small RAII guard"),
       hw(3), midterm("raii"), final("core")], True),
    S("cpp.smart-pointers", "cpp", "unique_ptr, shared_ptr, weak_ptr",
      "You can own an object with unique_ptr by default, justify shared_ptr only for genuinely shared lifetime, and say why its atomic refcount does not belong on a hot path.",
      3, [], 3,
      [deck(3, "w3", "slides 21\u201323"),
       lab(3, 3, "steps 2 and 5 \u2014 unique_ptr and the refcount tax"),
       hw(3), midterm("raii"), final("core")], True),
    S("perf.object-layout", "perf", "sizeof, padding & member ordering",
      "You can compute a struct's size from its members' alignment, shrink it by declaring the widest members first, and lock the layout in with static_assert.",
      3, [], 3,
      [deck(3, "w3", "slide 17"), midterm("ptr"), final("cache")]),
    S("perf.heap-nondeterminism", "perf", "Why the general allocator is non-deterministic",
      "You can explain why the same new call can take 20 ns or 20 \u00b5s \u2014 a lock, a free-list walk, fragmentation or a page fault \u2014 and why that variance lands in p99.9.",
      3, [4], 3,
      [deck(3, "w3", "slides 8, 27"), deck(4, "w4", "slide 5"),
       lab(3, 3, "step 6 \u2014 why on_book must not allocate"), final("sys")]),

    # ------------------------------------------------------------- session 4
    S("perf.object-pool", "perf", "Fixed-size object pools",
      "You can implement a fixed-size object pool whose free slots hold the free-list, so allocate and free are O(1) pointer swaps that never call the system allocator.",
      4, [7], 3,
      [deck(4, "w4", "slides 8, 10, 15"), deck(7, "w8", "slide 7"),
       lab(4, 4, "steps 3\u20134 \u2014 alloc and free in O(1)"), hw(4), proj(1), final("sys")], True),
    S("cpp.placement-new", "cpp", "Placement new & explicit destruction",
      "You can construct an object into storage you already own with placement new, and destroy it by calling its destructor explicitly before reusing the slot.",
      4, [], 2,
      [deck(4, "w4", "slides 9\u201310"), lab(4, 4, "step 5 \u2014 placement new + explicit dtor"),
       hw(4), midterm("raii")]),
    S("perf.arena-allocator", "perf", "Arena / bump allocation and per-tick scratch",
      "You can allocate a tick's scratch from a bump pointer over a pre-owned slab, align each request, and reclaim everything with one O(1) reset.",
      4, [], 3,
      [deck(4, "w4", "slides 9, 13, 15"), hw(4), proj(1), final("sys")]),
    S("cpp.pmr", "cpp", "std::pmr memory resources",
      "You can hand a standard container your own memory by constructing a pmr container over a monotonic_buffer_resource on a stack buffer.",
      4, [], 2,
      [deck(4, "w4", "slides 12\u201313, 15"), hw(4)]),

    # ------------------------------------------------------------- session 5
    S("cpp.templates", "cpp", "Function & class templates",
      "You can write a function or class template, let the compiler deduce its arguments, specialise the one type that deserves hand-tuning, and say why templates live in headers.",
      5, [], 3,
      [deck(5, "w5", "slides 5\u20137, 15"),
       lab(5, 5, "steps 1\u20132 \u2014 a code stamp and a generic container"),
       hw(5), midterm("tpl"), final("tpl")], True),
    S("cpp.variadic-templates", "cpp", "Parameter packs, folds & perfect forwarding",
      "You can take an arbitrary argument list with a parameter pack, collapse it with a fold expression, and forward each argument on without adding a copy.",
      5, [], 3,
      [deck(5, "w5", "slides 9\u201310, 27"),
       lab(5, 5, "step 3 \u2014 variadic template + fold expression"), hw(5), midterm("tpl")]),
    S("cpp.type-traits-constraints", "cpp", "Type traits, SFINAE, if constexpr & concepts",
      "You can ask a question about a type at compile time and use the answer to select or reject an overload \u2014 with enable_if, if constexpr, or a named C++20 concept.",
      5, [], 3,
      [deck(5, "w5", "slides 12\u201314"), deck(5, "w6", "slides 8\u20139"),
       lab(5, 5, "steps 4\u20135 \u2014 if constexpr and SFINAE"), hw(5), midterm("tpl")]),
    S("cpp.virtual-dispatch", "cpp", "Inheritance, virtual functions & abstract interfaces",
      "You can define an abstract interface with pure virtual functions and a virtual destructor, use override and final correctly, and spot the slicing and delete-through-a-non-virtual-base bugs.",
      5, [], 3,
      [deck(5, "w5", "slides 16\u201318, 24"),
       lab(5, 6, "step 1 \u2014 the virtual version we replace"), midterm("oop"), final("core")], True),
    S("perf.virtual-cost", "perf", "What a virtual call costs",
      "You can describe the vptr/vtable indirection, explain that the real bill is the indirect branch and the inlining you lose, and say where a virtual still belongs in a trading system.",
      5, [], 3,
      [deck(5, "w5", "slides 19\u201323, 25"),
       lab(5, 6, "step 2 \u2014 CRTP against the virtual baseline"), midterm("oop"), final("core")], True),
    S("cpp.constexpr", "cpp", "constexpr, consteval & static_assert",
      "You can compute a lookup table at compile time, check an assumption with static_assert so a violated invariant fails the build, and say what consteval forbids.",
      5, [], 3,
      [deck(5, "w6", "slides 5\u20136"), lab(5, 6, "step 3 \u2014 a constexpr lookup table"),
       hw(6), midterm("tpl")], True),
    S("cpp.crtp-policies", "cpp", "CRTP & policy-based design",
      "You can replace a virtual hierarchy with a base templated on its derived type, and compose behaviour from policy template parameters that cost nothing at run time.",
      5, [], 3,
      [deck(5, "w6", "slides 11\u201312"), lab(5, 6, "steps 2 and 4 \u2014 CRTP and policies"),
       hw(6), midterm("tpl"), final("tpl")], True),
    S("cpp.variant-visit", "cpp", "std::variant + compile-time visitor dispatch",
      "You can mirror a tagged wire union as a std::variant and dispatch it with a visitor whose dead branches are discarded at compile time \u2014 no vtable, no allocation.",
      5, [], 3,
      [deck(5, "w5", "slide 22"), deck(5, "w6", "slides 13\u201314"),
       lab(5, 6, "step 5 \u2014 variant + visitor dispatch"), hw(6), proj(1)]),

    # ------------------------------------------------------------- session 6
    S("perf.open-addressing-hash", "perf", "Open-addressing hash maps",
      "You can implement a flat open-addressing hash map with a power-of-two mask and linear probing, and explain why it beats a chaining map in cache.",
      6, [7], 3,
      [deck(6, "w7", "slides 5\u20136"), deck(7, "w8", "slide 15"),
       lab(6, 7, "step 7 \u2014 SymMap, open addressing"), hw(7), final("sys")], True),
    S("cpp.stl-containers", "cpp", "Choosing an STL container for an access pattern",
      "You can choose between std::map, std::unordered_map and a heap for ordered iteration, point lookup or best-element access, and state the cache cost of each.",
      6, [7], 2,
      [deck(6, "w7", "slide 7"), deck(7, "w8", "slide 6"),
       lab(6, 7, "step 1 \u2014 why not just std::map"), hw(7), midterm("stl"), final("tpl")]),
    S("trading.flat-order-book", "trading", "A flat, price-indexed local order book",
      "You can mirror an exchange book as a contiguous price-indexed level array with a cached top-of-book, so add, cancel and reading the touch stay O(1).",
      6, [], 3,
      [deck(6, "w7", "slides 9\u201311, 15"),
       lab(6, 7, "steps 2\u20136 \u2014 the level array, best_bid/best_ask, cancel"),
       hw(7), proj(2), final("sys")]),
    S("trading.queue-position", "trading", "Tracking your queue position",
      "You can track how much size rests ahead of your order at a price level and use that queue_ahead to judge your fill probability.",
      6, [13], 3,
      [deck(6, "w7", "slides 13\u201315"), deck(13, "w15", "slide 10"),
       hw(7), proj(2), final("sys")]),

    # ------------------------------------------------------------- session 7
    S("perf.complexity-in-cache-terms", "perf", "Complexity counted in cache misses",
      "You can argue about cost in memory accesses rather than instructions, and show why a linear scan over a small contiguous array beats an O(log n) walk over heap nodes.",
      7, [], 3,
      [deck(7, "w8", "slides 5\u20137"), lab(7, 8, "step 1 \u2014 the complexity framing"),
       midterm("cx"), final("tpl")]),
    S("perf.amortized-reserve", "perf", "Amortized cost & reserving up front",
      "You can explain why vector push_back is O(1) amortized and why reserving up front removes the occasional reallocation from your tail.",
      7, [], 2,
      [deck(7, "w8", "slides 5, 7"), midterm("stl"), final("meas")]),
    S("cpp.ring-buffer", "cpp", "A fixed-capacity ring buffer",
      "You can implement a fixed-capacity ring buffer over inline array storage with O(1) push, overwriting or expiring the oldest entry and never allocating.",
      7, [], 3,
      [deck(7, "w8", "slides 9\u201310"),
       lab(7, 8, "steps 2\u20135 \u2014 a ring of timestamps"), hw(8), final("sys")]),
    S("perf.incremental-computation", "perf", "Update, don't recompute",
      "You can replace a windowed recompute with an online update \u2014 a running mean, Welford variance or EMA \u2014 so every tick costs the same O(1) and the tail stays flat.",
      7, [], 3,
      [deck(7, "w8", "slides 12\u201313"),
       lab(7, 8, "step 7 \u2014 Welford's online mean/variance"), hw(8), final("meas")]),
    S("trading.obi-signal", "trading", "Turning microprice and imbalance into a signal",
      "You can fold microprice and order-book imbalance into online state and gate an order on a z-score, without looping a window on the hot path.",
      7, [], 2,
      [deck(7, "w8", "slides 14\u201315"), hw(8), proj(2)]),

    # ------------------------------------------------------------- session 8
    S("cpp.threads", "cpp", "std::thread and shared state",
      "You can start and join a std::thread and say which state is private to a thread and which is shared through the address space.",
      8, [], 2,
      [deck(8, "w9", "slide 5"), lab(8, 9, "step 1 \u2014 reproduce the race"), final("thr")]),
    S("cpp.data-races", "cpp", "Data races & happens-before",
      "You can identify a data race, explain that it is undefined behaviour rather than merely a wrong value, and name the happens-before edge that would make the access legal.",
      8, [], 3,
      [deck(8, "w9", "slides 6\u20137"),
       lab(8, 9, "steps 1\u20133 \u2014 the race, TSan, and the volatile non-fix"),
       hw(9), final("thr")], True),
    S("cpp.atomics-memory-order", "cpp", "std::atomic & memory ordering",
      "You can choose relaxed, acquire/release or seq_cst for each atomic operation and justify it with the happens-before edge you actually need.",
      8, [9], 3,
      [deck(8, "w9", "slides 9\u201312, 17"), deck(9, "w10", "slide 14"),
       lab(8, 9, "steps 4\u20135 \u2014 atomic, then acquire/release"), hw(9), final("atom")], True),
    S("cpp.mutex-toolbox", "cpp", "Mutexes, shared_mutex & condition variables",
      "You can take a mutex through a lock_guard, pick shared_mutex for read-mostly state, and wait on a condition variable with a predicate.",
      8, [], 2,
      [deck(8, "w9", "slide 14"),
       lab(8, 9, "step 6 \u2014 the mutex answer, correct but slow"), final("thr")]),
    S("perf.lock-tail-cost", "perf", "Why a lock on the hot path is a tail bomb",
      "You can trace how a contended mutex becomes a kernel wait or a priority inversion, and show the damage in p99.9 rather than in the median.",
      8, [], 3,
      [deck(8, "w9", "slides 15\u201316"),
       lab(8, 9, "step 6 \u2014 mutex against the atomic version"), hw(9), final("atom")], True),
    S("tools.thread-sanitizer", "tools", "Finding races with ThreadSanitizer",
      "You can build a target with -fsanitize=thread, run it under load, and use the report to name the two accesses that race.",
      8, [9, 12], 2,
      [deck(12, "w14", "slide 15"), lab(8, 9, "step 2 \u2014 let ThreadSanitizer name it"),
       lab(9, 10, "step 8 \u2014 two threads + ThreadSanitizer"), proj(3), final("meas")]),

    # ------------------------------------------------------------- session 9
    S("cpp.compare-and-swap", "cpp", "Compare-and-swap retry loops",
      "You can write a compare_exchange retry loop, explain why the expected value is refreshed on failure, and choose weak over strong inside a loop.",
      9, [], 3,
      [deck(9, "w10", "slide 5"), final("atom")], True),
    S("cpp.lock-free-guarantees", "cpp", "ABA & progress guarantees",
      "You can describe the ABA problem and distinguish wait-free, lock-free and obstruction-free progress guarantees.",
      9, [], 2,
      [deck(9, "w10", "slide 6"), final("atom")]),
    S("perf.spsc-ring", "perf", "A lock-free SPSC ring buffer",
      "You can build a bounded single-producer/single-consumer ring with atomic head and tail, a power-of-two mask, release/acquire publication, and the two indices on separate cache lines.",
      9, [], 3,
      [deck(9, "w10", "slides 8, 14"),
       lab(9, 10, "steps 2\u20136 \u2014 mask, alignas(64), push and pop"),
       hw(10), proj(3), final("atom")], True),
    S("perf.back-pressure", "perf", "Bounded queues & back-pressure",
      "You can make a full queue a decision \u2014 drop, coalesce or shed \u2014 instead of a stall, and explain how head-of-line blocking turns one fat message into a tail.",
      9, [10], 3,
      [deck(9, "w10", "slide 9"), deck(10, "w12", "slide 14"), hw(10), proj(3), final("atom")]),
    S("cpp.cpp20-coordination", "cpp", "C++20 coordination & execution policies",
      "You can line threads up with a latch or barrier instead of a hand-rolled condition variable, and say when an execution policy on an STL algorithm is worth its overhead.",
      9, [], 2,
      [deck(9, "w10", "slides 11\u201312"),
       lab(9, 10, "step 8 \u2014 the two-thread timed run"), final("thr")]),

    # ------------------------------------------------------------- session 10
    S("trading.fix-protocol", "trading", "Parsing FIX tag=value messages",
      "You can pull the fields you need out of a SOH-delimited FIX message in one forward scan and reject the message on a bad mod-256 checksum.",
      10, [], 3,
      [deck(10, "w11", "slides 5, 13, 15"),
       lab(10, 11, "steps 1\u20134 \u2014 one forward scan, dispatch on the tag"),
       hw(11), final("net")]),
    S("trading.binary-market-data", "trading", "Fixed-width binary market data",
      "You can decode an ITCH/OUCH-style fixed-width message by reading fields at known offsets, byte-swapping from network order and scaling integer prices, with no digit parsing.",
      10, [], 3,
      [deck(10, "w11", "slides 6\u20137, 16"),
       lab(10, 11, "step 6 \u2014 why fixed-width binary beats text"), hw(11), final("net")]),
    S("tools.message-framing", "tools", "Framing a byte stream into messages",
      "You can recover message boundaries from a stream with a length prefix or a delimiter, buffer a partial read, and bounds-check a length before you index with it.",
      10, [], 3,
      [deck(10, "w11", "slides 12\u201313"), deck(10, "w12", "slides 8, 14"),
       hw(11), final("net")]),
    S("trading.feed-sequencing", "trading", "Sequence numbers, gaps & snapshot-plus-increment",
      "You can rebuild a book from a snapshot plus increments, detect a sequence gap, and treat the book as untradeable until the feed has recovered.",
      10, [], 2,
      [deck(10, "w11", "slides 10, 13"), final("net")]),
    S("perf.transport-choice", "perf", "TCP vs UDP multicast for market data",
      "You can say why venues ship market data over UDP multicast and take order entry over TCP, and what head-of-line blocking and A/B feed arbitration mean for each.",
      10, [], 2,
      [deck(10, "w11", "slide 9"),
       lab(10, 11, "step 5 \u2014 TCP vs UDP semantics"), final("net")]),
    S("perf.nonblocking-io", "perf", "Non-blocking sockets & readiness event loops",
      "You can drain a non-blocking socket until EAGAIN inside an epoll or kqueue readiness loop, and explain what edge-triggered mode obliges you to do.",
      10, [], 2,
      [deck(10, "w12", "slides 5\u20138"),
       lab(10, 12, "step 5 \u2014 a non-blocking read loop"), final("net")]),
    S("perf.zero-copy-parse", "perf", "Zero-copy parse & hand-rolled serialization",
      "You can pull only the fields you use straight out of a frame with a view instead of building a DOM, write digits into a reused buffer on the send path, and show the p99.9 win on a replay tape.",
      10, [], 3,
      [deck(10, "w12", "slides 10\u201312, 17"),
       lab(10, 12, "steps 1\u20134 and 6 \u2014 fast integer-to-decimal and targeted JSON extract"),
       hw(12), proj(4), final("net")]),
    S("perf.batching-vs-latency", "perf", "Batching vs latency",
      "You can explain why batching buys throughput at the cost of the tail you are graded on, and why TCP_NODELAY belongs on an order path.",
      10, [], 2,
      [deck(10, "w12", "slide 15"), final("meas")]),

    # ------------------------------------------------------------- session 11
    S("perf.simd", "perf", "SIMD & vectorization",
      "You can vectorize a hot reduction with AVX2 intrinsics over 32-byte-aligned data, or get the compiler to do it with -O3 -march=native, and check that it really vectorized.",
      11, [], 3,
      [deck(11, "w13", "slides 7, 16"),
       lab(11, 13, "steps 2 and 5 \u2014 the winning build, then the intrinsics by hand"),
       hw(13), proj(5), final("simd")], True),
    S("perf.prefetch", "perf", "Software prefetching & the TLB",
      "You can issue a __builtin_prefetch hint ahead of an irregular walk, tune the distance by measurement, and say how huge pages cut TLB misses.",
      11, [], 2,
      [deck(11, "w13", "slides 5\u20136, 16"),
       lab(11, 13, "step 6 \u2014 alignas and __builtin_prefetch"), proj(5), final("simd")]),
    S("perf.syscall-cost", "perf", "Syscalls, busy-poll & interrupt jitter",
      "You can explain what a trip into the kernel costs on a hot path and when busy-polling a queue beats waiting to be woken.",
      11, [], 2,
      [deck(11, "w13", "slide 9"), final("net")]),
    S("perf.kernel-bypass", "perf", "What kernel bypass changes",
      "You can explain what kernel bypass changes \u2014 DPDK, an Onload-style shim, or io_uring's batched syscalls \u2014 and which per-packet kernel costs each one removes.",
      11, [], 1,
      [deck(11, "w13", "slide 10"), final("net")], True),
    S("perf.cpu-pinning-numa", "perf", "CPU pinning, core isolation & NUMA",
      "You can pin a hot thread to a core, say what isolcpus and nohz_full add, and keep its memory node-local and pre-faulted so no page fault lands mid-race.",
      11, [], 2,
      [deck(11, "w13", "slides 11, 15"),
       lab(11, 13, "step 7 \u2014 connect it to the arena"), proj(5), final("sys")]),
    S("tools.compiler-flags", "tools", "Release flags, LTO & PGO",
      "You can justify -O3, -march=native, -flto and -DNDEBUG on a graded binary, keep -g for the profiler, and run the two-pass profile-guided build.",
      11, [12], 3,
      [deck(11, "w13", "slide 16"), deck(12, "w14", "slides 12, 14"),
       lab(11, 13, "steps 2\u20134 \u2014 the winning build and PGO"), hw(13), final("simd")]),
    S("perf.hardware-timestamping", "perf", "PTP & hardware timestamping",
      "You can explain why NTP is too coarse for microsecond work and what a NIC hardware timestamp measures that a user-space clock read cannot.",
      11, [], 1,
      [deck(11, "w13", "slides 13\u201314"), final("meas")]),

    # ------------------------------------------------------------- session 12
    S("tools.perf-profiler", "tools", "Profiling with perf",
      "You can go from perf stat to perf record to perf report and annotate, and read cache-miss and branch-miss counters to say why a hot line is hot.",
      12, [], 3,
      [deck(12, "w14", "slides 6\u20138"),
       lab(12, 14, "step 3 \u2014 perf record then perf report"), hw(14), proj(6), final("meas")], True),
    S("tools.flame-graph", "tools", "Reading a flame graph",
      "You can fold sampled stacks into a flame graph and read it by width, so the wide plateaus rather than the tall spikes set your next fix.",
      12, [], 2,
      [deck(12, "w14", "slide 7"), hw(14), proj(6), final("meas")]),
    S("perf.tail-diagnosis", "perf", "Diagnosing a latency tail",
      "You can attribute a tail spike to allocation, a page fault, a TLB miss, NUMA locality or scheduler preemption from its signature, then fix it and prove the p99.9 moved.",
      12, [], 3,
      [deck(12, "w14", "slides 5, 10\u201311, 17"),
       lab(12, 14, "steps 1\u20135 \u2014 read the tail, hypothesise, fix, watch it collapse"),
       hw(14), proj(6), final("meas")], True),
    S("tools.sanitizers", "tools", "AddressSanitizer & UBSan",
      "You can build with -fsanitize=address,undefined, read the report back to the offending line, and explain why a sanitizer build is never the one you ship.",
      12, [], 2,
      [deck(12, "w14", "slides 15, 18"),
       lab(12, 14, "step 6 \u2014 the bugs that become tails"), hw(14), final("meas")]),
    S("tools.async-logging", "tools", "Logging & monitoring off the hot path",
      "You can keep observability off the hot path by pushing fixed-size records into a lock-free ring for another thread to format, and watch p99.9 live instead of only at session end.",
      12, [], 2,
      [deck(12, "w14", "slide 16"), proj(6), final("meas")]),

    # ------------------------------------------------------------- session 13
    S("trading.nbbo-latency-arb", "trading", "The NBBO & picking off a stale quote",
      "You can consolidate two venues into an NBBO, detect the crossed state that means one side is stale, and explain why only the first order to reach that venue is paid.",
      13, [], 3,
      [deck(13, "w15", "slides 5\u20136, 17"),
       lab(13, 15, "step 2 \u2014 the cross-venue stale-quote detector"),
       hw(15), proj(7), final("sys")]),
    S("trading.smart-order-routing", "trading", "Smart order routing & sweeping",
      "You can split or sweep an order across venues for displayed size and account for fees, rebates and per-venue latency in the route you pick.",
      13, [], 2,
      [deck(13, "w15", "slide 7"), proj(7), final("sys")]),
    S("trading.market-making", "trading", "Quoting two sides at speed",
      "You can quote a bid and an ask around a fair value anchored on the microprice, and explain how spread plus rebates pay for the risk of a stale quote.",
      13, [], 3,
      [deck(13, "w15", "slide 9"),
       lab(13, 15, "step 4 \u2014 map strategy to the composite grade"), proj(7), final("sys")]),
    S("trading.queue-aware-requoting", "trading", "Queue-aware requoting & inventory skew",
      "You can decide when a requote is worth losing your place in the FIFO queue, and lean your quotes against the inventory you are carrying.",
      13, [], 2,
      [deck(13, "w15", "slide 10"),
       lab(13, 15, "step 3 \u2014 sketch the queue-aware requote"), proj(7), final("sys")]),
    S("trading.adverse-selection", "trading", "Adverse selection & markouts",
      "You can mark a fill out against the mid a moment later and use a persistently negative markout to widen, skew away from, or stop quoting a name.",
      13, [], 3,
      [deck(13, "w15", "slide 11"), hw(15), proj(7), final("sys")]),
    S("trading.hft-ethics", "trading", "The frontier and the ethics of speed",
      "You can argue both sides of paid speed \u2014 tighter spreads and deeper books against a pay-to-win arms race \u2014 and name the rules that shape it.",
      13, [], 1,
      [deck(13, "w15", "slides 13\u201314")]),
]

# ---------------------------------------------------------------- assemble
def build():
    order = {s["id"]: i for i, s in enumerate(SKILLS)}
    sessions = []
    for n, date, title, decks, labs, hwn, phase, exam in SESSIONS:
        intro = sorted([s["id"] for s in SKILLS if s["introduced"] == n], key=order.get)
        prac = sorted([s["id"] for s in SKILLS if n in s["practised"]], key=order.get)
        hid, hname, hdue = HW[hwn]
        pid, pname, pdue = PH[phase]
        sessions.append({
            "n": n, "date": date, "title": title, "decks": decks,
            "lab": {"label": "Lab — Week %d" % labs[0], "url": "%sweek%02d.md" % (LABS, labs[0])},
            "hw": {"label": hname, "url": CANVAS + str(hid), "due": hdue},
            "project": {"label": pname, "url": CANVAS + str(pid), "due": pdue},
            "exam": exam,
            "companion_url": "%sweek%s.html" % (COMP, decks[0][1:]),
            "skills": intro + prac,
        })
    return {
        "course": {
            "code": "IEOR E4741",
            "title": "High-Frequency Trading Systems in C++",
            "institution": "Columbia University",
            "term": "Fall 2026",
            "sessions_url": "https://courseworks2.columbia.edu/courses/252758",
            "starter_url": "https://github.com/sdonadio/hft-cpp-starter-columbia",
            "companion_url": COMP,
        },
        "categories": [
            {"id": "cpp", "name": "C++ language", "color": "#1D4F91"},
            {"id": "perf", "name": "Systems & performance", "color": "#C8102E"},
            {"id": "tools", "name": "Tooling & engineering", "color": "#2E8B57"},
            {"id": "trading", "name": "Trading & microstructure", "color": "#B8860B"},
        ],
        "sessions": sessions,
        "skills": SKILLS,
    }


if __name__ == "__main__":
    data = build()
    with open(OUT, "w") as f:
        f.write("window.SKILLS = ")
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write(";\n")
    print("wrote", OUT, len(SKILLS), "skills")
